sensing/camera/camera_node:
  ros__parameters:
    image_width: 640
    image_height: 480
    camera_name: imx219_camera
    camera_matrix: [739.597426, 0.0, 314.611856,
                    0.0, 733.874660, 234.692425,
                    0.0, 0.0, 1.0]
    distortion_model: plumb_bob
    distortion_coefficients: [-0.098590, 0.100049, -0.001107, 0.002149, 0.000000]
    rectification_matrix: [1.0, 0.0, 0.0,
                          0.0, 1.0, 0.0,
                          0.0, 0.0, 1.0]
    projection_matrix: [728.343573, 0.0, 315.434048, 0.0,
                        0.0, 726.861236, 234.340955, 0.0,
                        0.0, 0.0, 1.0, 0.0]