; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = firmware

[env]
platform = teensy
board = teensy41
framework = arduino
upload_protocol = teensy-gui
board_microros_distro = jazzy
board_microros_transport = serial
board_microros_user_meta = colcon.meta
board_microros_extra_packages = ackermann_msgs
; build_flags = -Wno-deprecated
monitor_port = /dev/ttyACM0
monitor_speed = 115200
; monitor_echo = false
monitor_eol = CRLF
monitor_filters =
    ; debug
    time
    send_on_enter

lib_deps =
    https://github.com/micro-ROS/micro_ros_platformio
    siteswapjuggler/Ramp


build_flags =
    -D USB_DUAL_SERIAL
    -D RCUTILS_LOG_MIN_SEVERITY=RCUTILS_LOG_SEVERITY_DEBUG

[env:firmware]
build_src_filter = +<main.cpp> +<*/**>
lib_deps =
    ${env.lib_deps}

[env:configure_steering]
build_src_filter = +<configure_steering.cpp> +<*/**>
lib_deps =
    ${env.lib_deps}

[env:configure_propulsion]
build_src_filter = +<configure_propulsion.cpp> +<*/**>
lib_deps =
    ${env.lib_deps}

[env:test]
build_src_filter = +<test.cpp>
lib_deps =
    ${env.lib_deps}
